#!/bin/sh

ic=${1:-''}

d='data'
p='progress'
dir="$HOME/projects/Python/NBody3D"
jar='target/orbits-0.0.1-SNAPSHOT-jar-with-dependencies.jar'

java -jar $jar $ic >$d 2>$p &
PID=$!
sleep 1
$dir/filegraphics.py $d $p &
wait $PID
set $(wc -l $p)
$dir/fileprogress.py $p $(($1 / 10000)) &

